<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" version="3.0.2" name="TestSuite" time="24.448" tests="45" errors="0" skipped="24" failures="21">
  <properties>
    <property name="java.specification.version" value="21"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.class.path" value="/Users/administrator/eclipse-workspace/AppiumFrameworkCloud/target/test-classes:/Users/administrator/eclipse-workspace/AppiumFrameworkCloud/target/classes:/Users/administrator/.m2/repository/io/appium/java-client/9.5.0/java-client-9.5.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-api/4.34.0/selenium-api-4.34.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/4.34.0/selenium-remote-driver-4.34.0.jar:/Users/administrator/.m2/repository/com/google/auto/service/auto-service-annotations/1.1.1/auto-service-annotations-1.1.1.jar:/Users/administrator/.m2/repository/com/google/guava/guava/33.4.8-jre/guava-33.4.8-jre.jar:/Users/administrator/.m2/repository/com/google/guava/failureaccess/1.0.3/failureaccess-1.0.3.jar:/Users/administrator/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/administrator/.m2/repository/com/google/j2objc/j2objc-annotations/3.0.0/j2objc-annotations-3.0.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-api/1.51.0/opentelemetry-api-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-context/1.51.0/opentelemetry-context-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-exporter-logging/1.51.0/opentelemetry-exporter-logging-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk-common/1.51.0/opentelemetry-sdk-common-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/1.51.0/opentelemetry-sdk-extension-autoconfigure-spi-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk-extension-autoconfigure/1.51.0/opentelemetry-sdk-extension-autoconfigure-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk-trace/1.51.0/opentelemetry-sdk-trace-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk/1.51.0/opentelemetry-sdk-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk-metrics/1.51.0/opentelemetry-sdk-metrics-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk-logs/1.51.0/opentelemetry-sdk-logs-1.51.0.jar:/Users/administrator/.m2/repository/net/bytebuddy/byte-buddy/1.17.6/byte-buddy-1.17.6.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-http/4.34.0/selenium-http-4.34.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-json/4.34.0/selenium-json-4.34.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-manager/4.34.0/selenium-manager-4.34.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-os/4.34.0/selenium-os-4.34.0.jar:/Users/administrator/.m2/repository/org/apache/commons/commons-exec/1.5.0/commons-exec-1.5.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-support/4.34.0/selenium-support-4.34.0.jar:/Users/administrator/.m2/repository/com/google/code/gson/gson/2.13.1/gson-2.13.1.jar:/Users/administrator/.m2/repository/com/google/errorprone/error_prone_annotations/2.38.0/error_prone_annotations-2.38.0.jar:/Users/administrator/.m2/repository/org/slf4j/slf4j-api/2.0.17/slf4j-api-2.0.17.jar:/Users/administrator/.m2/repository/org/jspecify/jspecify/1.0.0/jspecify-1.0.0.jar:/Users/administrator/.m2/repository/org/testng/testng/7.10.2/testng-7.10.2.jar:/Users/administrator/.m2/repository/com/beust/jcommander/1.82/jcommander-1.82.jar:/Users/administrator/.m2/repository/org/webjars/jquery/3.7.1/jquery-3.7.1.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-java/4.33.0/selenium-java-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/4.33.0/selenium-chrome-driver-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-chromium-driver/4.33.0/selenium-chromium-driver-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v135/4.33.0/selenium-devtools-v135-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v136/4.33.0/selenium-devtools-v136-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v137/4.33.0/selenium-devtools-v137-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/4.33.0/selenium-edge-driver-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/4.33.0/selenium-firefox-driver-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/4.33.0/selenium-ie-driver-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/4.33.0/selenium-safari-driver-4.33.0.jar:/Users/administrator/.m2/repository/commons-io/commons-io/2.19.0/commons-io-2.19.0.jar:/Users/administrator/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.19.1/jackson-databind-2.19.1.jar:/Users/administrator/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.19.1/jackson-annotations-2.19.1.jar:/Users/administrator/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.19.1/jackson-core-2.19.1.jar:/Users/administrator/.m2/repository/com/aventstack/extentreports/5.0.9/extentreports-5.0.9.jar:/Users/administrator/.m2/repository/io/reactivex/rxjava3/rxjava/3.0.4/rxjava-3.0.4.jar:/Users/administrator/.m2/repository/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar:/Users/administrator/.m2/repository/org/freemarker/freemarker/2.3.30/freemarker-2.3.30.jar:/Users/administrator/.m2/repository/org/projectlombok/lombok/1.18.28/lombok-1.18.28.jar:/Users/administrator/.m2/repository/com/browserstack/browserstack-java-sdk/1.38.1/browserstack-java-sdk-1.38.1.jar:"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.vendor.url" value="https://java.oracle.com/"/>
    <property name="user.timezone" value="America/New_York"/>
    <property name="os.name" value="Mac OS X"/>
    <property name="java.vm.specification.version" value="21"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="user.country" value="US"/>
    <property name="BROWSERSTACK_LOG_DIR" value="/Users/administrator/eclipse-workspace/AppiumFrameworkCloud/log"/>
    <property name="sun.boot.library.path" value="/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/lib"/>
    <property name="sun.java.command" value="/Users/administrator/eclipse-workspace/AppiumFrameworkCloud/target/surefire/surefirebooter-20250724105315532_3.jar /Users/administrator/eclipse-workspace/AppiumFrameworkCloud/target/surefire 2025-07-24T10-53-15_502-jvmRun1 surefire-20250724105315532_1tmp surefire_0-20250724105315532_2tmp"/>
    <property name="http.nonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
    <property name="jdk.debug" value="release"/>
    <property name="surefire.test.class.path" value="/Users/administrator/eclipse-workspace/AppiumFrameworkCloud/target/test-classes:/Users/administrator/eclipse-workspace/AppiumFrameworkCloud/target/classes:/Users/administrator/.m2/repository/io/appium/java-client/9.5.0/java-client-9.5.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-api/4.34.0/selenium-api-4.34.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/4.34.0/selenium-remote-driver-4.34.0.jar:/Users/administrator/.m2/repository/com/google/auto/service/auto-service-annotations/1.1.1/auto-service-annotations-1.1.1.jar:/Users/administrator/.m2/repository/com/google/guava/guava/33.4.8-jre/guava-33.4.8-jre.jar:/Users/administrator/.m2/repository/com/google/guava/failureaccess/1.0.3/failureaccess-1.0.3.jar:/Users/administrator/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/administrator/.m2/repository/com/google/j2objc/j2objc-annotations/3.0.0/j2objc-annotations-3.0.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-api/1.51.0/opentelemetry-api-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-context/1.51.0/opentelemetry-context-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-exporter-logging/1.51.0/opentelemetry-exporter-logging-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk-common/1.51.0/opentelemetry-sdk-common-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk-extension-autoconfigure-spi/1.51.0/opentelemetry-sdk-extension-autoconfigure-spi-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk-extension-autoconfigure/1.51.0/opentelemetry-sdk-extension-autoconfigure-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk-trace/1.51.0/opentelemetry-sdk-trace-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk/1.51.0/opentelemetry-sdk-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk-metrics/1.51.0/opentelemetry-sdk-metrics-1.51.0.jar:/Users/administrator/.m2/repository/io/opentelemetry/opentelemetry-sdk-logs/1.51.0/opentelemetry-sdk-logs-1.51.0.jar:/Users/administrator/.m2/repository/net/bytebuddy/byte-buddy/1.17.6/byte-buddy-1.17.6.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-http/4.34.0/selenium-http-4.34.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-json/4.34.0/selenium-json-4.34.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-manager/4.34.0/selenium-manager-4.34.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-os/4.34.0/selenium-os-4.34.0.jar:/Users/administrator/.m2/repository/org/apache/commons/commons-exec/1.5.0/commons-exec-1.5.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-support/4.34.0/selenium-support-4.34.0.jar:/Users/administrator/.m2/repository/com/google/code/gson/gson/2.13.1/gson-2.13.1.jar:/Users/administrator/.m2/repository/com/google/errorprone/error_prone_annotations/2.38.0/error_prone_annotations-2.38.0.jar:/Users/administrator/.m2/repository/org/slf4j/slf4j-api/2.0.17/slf4j-api-2.0.17.jar:/Users/administrator/.m2/repository/org/jspecify/jspecify/1.0.0/jspecify-1.0.0.jar:/Users/administrator/.m2/repository/org/testng/testng/7.10.2/testng-7.10.2.jar:/Users/administrator/.m2/repository/com/beust/jcommander/1.82/jcommander-1.82.jar:/Users/administrator/.m2/repository/org/webjars/jquery/3.7.1/jquery-3.7.1.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-java/4.33.0/selenium-java-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/4.33.0/selenium-chrome-driver-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-chromium-driver/4.33.0/selenium-chromium-driver-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v135/4.33.0/selenium-devtools-v135-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v136/4.33.0/selenium-devtools-v136-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-devtools-v137/4.33.0/selenium-devtools-v137-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/4.33.0/selenium-edge-driver-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/4.33.0/selenium-firefox-driver-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/4.33.0/selenium-ie-driver-4.33.0.jar:/Users/administrator/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/4.33.0/selenium-safari-driver-4.33.0.jar:/Users/administrator/.m2/repository/commons-io/commons-io/2.19.0/commons-io-2.19.0.jar:/Users/administrator/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.19.1/jackson-databind-2.19.1.jar:/Users/administrator/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.19.1/jackson-annotations-2.19.1.jar:/Users/administrator/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.19.1/jackson-core-2.19.1.jar:/Users/administrator/.m2/repository/com/aventstack/extentreports/5.0.9/extentreports-5.0.9.jar:/Users/administrator/.m2/repository/io/reactivex/rxjava3/rxjava/3.0.4/rxjava-3.0.4.jar:/Users/administrator/.m2/repository/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar:/Users/administrator/.m2/repository/org/freemarker/freemarker/2.3.30/freemarker-2.3.30.jar:/Users/administrator/.m2/repository/org/projectlombok/lombok/1.18.28/lombok-1.18.28.jar:/Users/administrator/.m2/repository/com/browserstack/browserstack-java-sdk/1.38.1/browserstack-java-sdk-1.38.1.jar:"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="user.home" value="/Users/administrator"/>
    <property name="user.language" value="en"/>
    <property name="ipAddress" value="127.0.0.1"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="BROWSERSTACK_CLI_BIN_LISTEN_ADDR" value="127.0.0.1:5400"/>
    <property name="java.version.date" value="2025-04-15"/>
    <property name="java.home" value="/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home"/>
    <property name="file.separator" value="/"/>
    <property name="basedir" value="/Users/administrator/eclipse-workspace/AppiumFrameworkCloud"/>
    <property name="java.vm.compressedOopsMode" value="Zero based"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="apple.awt.application.name" value="ForkedBooter"/>
    <property name="surefire.real.class.path" value="/Users/administrator/eclipse-workspace/AppiumFrameworkCloud/target/surefire/surefirebooter-20250724105315532_3.jar"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="ftp.nonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
    <property name="java.runtime.version" value="21.0.7+8-LTS-245"/>
    <property name="user.name" value="administrator"/>
    <property name="stdout.encoding" value="UTF-8"/>
    <property name="path.separator" value=":"/>
    <property name="os.version" value="15.5"/>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="BROWSERSTACK_CLI_BIN_SESSION_ID" value="033132a9-489a-4866-859d-d5c80e9a339d"/>
    <property name="localRepository" value="/Users/administrator/.m2/repository"/>
    <property name="java.vendor.url.bug" value="https://bugreport.java.com/bugreport/"/>
    <property name="java.io.tmpdir" value="/var/folders/b5/zsb_c0_96m591__5t0hnl_q80000gn/T/"/>
    <property name="java.version" value="21.0.7"/>
    <property name="user.dir" value="/Users/administrator/eclipse-workspace/AppiumFrameworkCloud"/>
    <property name="os.arch" value="aarch64"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="native.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/Users/administrator/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:."/>
    <property name="java.vm.info" value="mixed mode, sharing"/>
    <property name="stderr.encoding" value="UTF-8"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="java.vm.version" value="21.0.7+8-LTS-245"/>
    <property name="sun.io.unicode.encoding" value="UnicodeBig"/>
    <property name="socksNonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
    <property name="java.class.version" value="65.0"/>
  </properties>
  <testcase name="configureAppium" classname="org.latiffsyed.tests.android.PurchaseOrderFlowTest" time="20.425">
    <failure message="Appium HTTP server is not listening at http://127.0.0.1:4723/ after 20000 ms timeout. Consider increasing the server startup timeout value and check the server log for possible error messages occurrences.&#10;Node.js executable path: /usr/local/bin/node&#10;Arguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 127.0.0.1]&#10;Server log: &amp;#27;[38;5;112m[Appium]&amp;#27;[0m Welcome to Appium v2.19.0&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Non-default server args:&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m { address: &amp;#27;[32m&apos;127.0.0.1&apos;&amp;#27;[39m }&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m The autodetected Appium home path: /Users/administrator/.appium&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Attempting to load driver uiautomator2...&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Attempting to load driver xcuitest...&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m XCUITestDriver has been successfully loaded in 0.491s&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.923s&#10;&amp;#27;[38;5;86m[HTTP]&amp;#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Could not configure Appium server. It&apos;s possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723&#10;    at Server.setupListenHandle [as _listen2] (node:net:1939:16)&#10;    at listenInCluster (node:net:1996:12)&#10;    at node:net:2205:7&#10;    at processTicksAndRejections (node:internal/process/task_queues:90:21)&#10;" type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException"><![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: 
Appium HTTP server is not listening at http://127.0.0.1:4723/ after 20000 ms timeout. Consider increasing the server startup timeout value and check the server log for possible error messages occurrences.
Node.js executable path: /usr/local/bin/node
Arguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 127.0.0.1]
Server log: &amp#27;[38;5;112m[Appium]&amp#27;[0m Welcome to Appium v2.19.0
&amp#27;[38;5;112m[Appium]&amp#27;[0m Non-default server args:
&amp#27;[38;5;112m[Appium]&amp#27;[0m { address: &amp#27;[32m'127.0.0.1'&amp#27;[39m }
&amp#27;[38;5;112m[Appium]&amp#27;[0m The autodetected Appium home path: /Users/administrator/.appium
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver uiautomator2...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver xcuitest...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m XCUITestDriver has been successfully loaded in 0.491s
&amp#27;[38;5;112m[Appium]&amp#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.923s
&amp#27;[38;5;86m[HTTP]&amp#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
&amp#27;[38;5;112m[Appium]&amp#27;[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
&amp#27;[38;5;112m[Appium]&amp#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (node:net:1939:16)
    at listenInCluster (node:net:1996:12)
    at node:net:2205:7
    at processTicksAndRejections (node:internal/process/task_queues:90:21)

	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:192)
	at org.latiffsyed.core.utils.AppiumUtils.startAppiumServer(AppiumUtils.java:35)
	at org.latiffsyed.testUtils.AndroidBaseTest.configureAppium(AndroidBaseTest.java:52)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.appium.java_client.service.local.AppiumServerAvailabilityChecker$ConnectionTimeout: ConnectionTimeout
	at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:72)
	at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:144)
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:185)
	... 20 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1319)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1252)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1138)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1067)
	at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.connectToUrl(AppiumServerAvailabilityChecker.java:79)
	at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:61)
	... 22 more
]]></failure>
    <system-out><![CDATA[Hello/Users/administrator/eclipse-workspace/AppiumFrameworkCloud//reports//index.html
>>> TestNG Listener: onStart()
>>> TestNG Listener: onStart()
>>> TestNG Listener: onStart()
&amp#27;[38;5;112m[Appium]&amp#27;[0m Welcome to Appium v2.19.0
&amp#27;[38;5;112m[Appium]&amp#27;[0m Welcome to Appium v2.19.0
&amp#27;[38;5;112m[Appium]&amp#27;[0m Welcome to Appium v2.19.0
&amp#27;[38;5;112m[Appium]&amp#27;[0m Non-default server args:
&amp#27;[38;5;112m[Appium]&amp#27;[0m Non-default server args:
&amp#27;[38;5;112m[Appium]&amp#27;[0m Non-default server args:
&amp#27;[38;5;112m[Appium]&amp#27;[0m { address: &amp#27;[32m'127.0.0.1'&amp#27;[39m }
&amp#27;[38;5;112m[Appium]&amp#27;[0m { address: &amp#27;[32m'127.0.0.1'&amp#27;[39m }
&amp#27;[38;5;112m[Appium]&amp#27;[0m { address: &amp#27;[32m'127.0.0.1'&amp#27;[39m }
&amp#27;[38;5;112m[Appium]&amp#27;[0m The autodetected Appium home path: /Users/administrator/.appium
&amp#27;[38;5;112m[Appium]&amp#27;[0m The autodetected Appium home path: /Users/administrator/.appium
&amp#27;[38;5;112m[Appium]&amp#27;[0m The autodetected Appium home path: /Users/administrator/.appium
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver uiautomator2...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver uiautomator2...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver uiautomator2...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver xcuitest...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver xcuitest...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver xcuitest...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m XCUITestDriver has been successfully loaded in 0.491s
&amp#27;[38;5;112m[Appium]&amp#27;[0m XCUITestDriver has been successfully loaded in 0.491s
&amp#27;[38;5;112m[Appium]&amp#27;[0m XCUITestDriver has been successfully loaded in 0.491s
&amp#27;[38;5;112m[Appium]&amp#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.923s
&amp#27;[38;5;112m[Appium]&amp#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.923s
&amp#27;[38;5;112m[Appium]&amp#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.923s
&amp#27;[38;5;86m[HTTP]&amp#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
&amp#27;[38;5;112m[Appium]&amp#27;[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
&amp#27;[38;5;112m[Appium]&amp#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (node:net:1939:16)
    at listenInCluster (node:net:1996:12)
    at node:net:2205:7
    at processTicksAndRejections (node:internal/process/task_queues:90:21)
&amp#27;[38;5;86m[HTTP]&amp#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
&amp#27;[38;5;86m[HTTP]&amp#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
&amp#27;[38;5;112m[Appium]&amp#27;[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
&amp#27;[38;5;112m[Appium]&amp#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (node:net:1939:16)
    at listenInCluster (node:net:1996:12)
    at node:net:2205:7
    at processTicksAndRejections (node:internal/process/task_queues:90:21)
&amp#27;[38;5;112m[Appium]&amp#27;[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
&amp#27;[38;5;112m[Appium]&amp#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (node:net:1939:16)
    at listenInCluster (node:net:1996:12)
    at node:net:2205:7
    at processTicksAndRejections (node:internal/process/task_queues:90:21)
]]></system-out>
    <system-err><![CDATA[SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
]]></system-err>
  </testcase>
  <testcase name="configureAppium" classname="org.latiffsyed.tests.android.PurchaseOrderFlowTest" time="20.427">
    <failure message="Appium HTTP server is not listening at http://127.0.0.1:4723/ after 20000 ms timeout. Consider increasing the server startup timeout value and check the server log for possible error messages occurrences.&#10;Node.js executable path: /usr/local/bin/node&#10;Arguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 127.0.0.1]&#10;Server log: &amp;#27;[38;5;112m[Appium]&amp;#27;[0m Welcome to Appium v2.19.0&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Non-default server args:&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m { address: &amp;#27;[32m&apos;127.0.0.1&apos;&amp;#27;[39m }&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m The autodetected Appium home path: /Users/administrator/.appium&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Attempting to load driver uiautomator2...&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Attempting to load driver xcuitest...&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m XCUITestDriver has been successfully loaded in 0.491s&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.923s&#10;&amp;#27;[38;5;86m[HTTP]&amp;#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Could not configure Appium server. It&apos;s possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723&#10;    at Server.setupListenHandle [as _listen2] (node:net:1939:16)&#10;    at listenInCluster (node:net:1996:12)&#10;    at node:net:2205:7&#10;    at processTicksAndRejections (node:internal/process/task_queues:90:21)&#10;" type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException"><![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: 
Appium HTTP server is not listening at http://127.0.0.1:4723/ after 20000 ms timeout. Consider increasing the server startup timeout value and check the server log for possible error messages occurrences.
Node.js executable path: /usr/local/bin/node
Arguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 127.0.0.1]
Server log: &amp#27;[38;5;112m[Appium]&amp#27;[0m Welcome to Appium v2.19.0
&amp#27;[38;5;112m[Appium]&amp#27;[0m Non-default server args:
&amp#27;[38;5;112m[Appium]&amp#27;[0m { address: &amp#27;[32m'127.0.0.1'&amp#27;[39m }
&amp#27;[38;5;112m[Appium]&amp#27;[0m The autodetected Appium home path: /Users/administrator/.appium
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver uiautomator2...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver xcuitest...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m XCUITestDriver has been successfully loaded in 0.491s
&amp#27;[38;5;112m[Appium]&amp#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.923s
&amp#27;[38;5;86m[HTTP]&amp#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
&amp#27;[38;5;112m[Appium]&amp#27;[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
&amp#27;[38;5;112m[Appium]&amp#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (node:net:1939:16)
    at listenInCluster (node:net:1996:12)
    at node:net:2205:7
    at processTicksAndRejections (node:internal/process/task_queues:90:21)

	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:192)
	at org.latiffsyed.core.utils.AppiumUtils.startAppiumServer(AppiumUtils.java:35)
	at org.latiffsyed.testUtils.AndroidBaseTest.configureAppium(AndroidBaseTest.java:52)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.appium.java_client.service.local.AppiumServerAvailabilityChecker$ConnectionTimeout: ConnectionTimeout
	at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:72)
	at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:144)
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:185)
	... 20 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1319)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1252)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1138)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1067)
	at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.connectToUrl(AppiumServerAvailabilityChecker.java:79)
	at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:61)
	... 22 more
]]></failure>
  </testcase>
  <testcase name="configureAppium" classname="org.latiffsyed.tests.android.PurchaseOrderFlowTest" time="20.427">
    <failure message="Appium HTTP server is not listening at http://127.0.0.1:4723/ after 20000 ms timeout. Consider increasing the server startup timeout value and check the server log for possible error messages occurrences.&#10;Node.js executable path: /usr/local/bin/node&#10;Arguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 127.0.0.1]&#10;Server log: &amp;#27;[38;5;112m[Appium]&amp;#27;[0m Welcome to Appium v2.19.0&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Non-default server args:&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m { address: &amp;#27;[32m&apos;127.0.0.1&apos;&amp;#27;[39m }&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m The autodetected Appium home path: /Users/administrator/.appium&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Attempting to load driver uiautomator2...&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Attempting to load driver xcuitest...&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m XCUITestDriver has been successfully loaded in 0.491s&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.923s&#10;&amp;#27;[38;5;86m[HTTP]&amp;#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Could not configure Appium server. It&apos;s possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723&#10;    at Server.setupListenHandle [as _listen2] (node:net:1939:16)&#10;    at listenInCluster (node:net:1996:12)&#10;    at node:net:2205:7&#10;    at processTicksAndRejections (node:internal/process/task_queues:90:21)&#10;" type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException"><![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: 
Appium HTTP server is not listening at http://127.0.0.1:4723/ after 20000 ms timeout. Consider increasing the server startup timeout value and check the server log for possible error messages occurrences.
Node.js executable path: /usr/local/bin/node
Arguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 127.0.0.1]
Server log: &amp#27;[38;5;112m[Appium]&amp#27;[0m Welcome to Appium v2.19.0
&amp#27;[38;5;112m[Appium]&amp#27;[0m Non-default server args:
&amp#27;[38;5;112m[Appium]&amp#27;[0m { address: &amp#27;[32m'127.0.0.1'&amp#27;[39m }
&amp#27;[38;5;112m[Appium]&amp#27;[0m The autodetected Appium home path: /Users/administrator/.appium
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver uiautomator2...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver xcuitest...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m XCUITestDriver has been successfully loaded in 0.491s
&amp#27;[38;5;112m[Appium]&amp#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.923s
&amp#27;[38;5;86m[HTTP]&amp#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
&amp#27;[38;5;112m[Appium]&amp#27;[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
&amp#27;[38;5;112m[Appium]&amp#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (node:net:1939:16)
    at listenInCluster (node:net:1996:12)
    at node:net:2205:7
    at processTicksAndRejections (node:internal/process/task_queues:90:21)

	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:192)
	at org.latiffsyed.core.utils.AppiumUtils.startAppiumServer(AppiumUtils.java:35)
	at org.latiffsyed.testUtils.AndroidBaseTest.configureAppium(AndroidBaseTest.java:52)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.appium.java_client.service.local.AppiumServerAvailabilityChecker$ConnectionTimeout: ConnectionTimeout
	at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:72)
	at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:144)
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:185)
	... 20 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1319)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1252)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1138)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1067)
	at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.connectToUrl(AppiumServerAvailabilityChecker.java:79)
	at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:61)
	... 22 more
]]></failure>
  </testcase>
  <testcase name="preSetup" classname="org.latiffsyed.tests.android.PurchaseOrderFlowTest" time="20.5">
    <failure message="Cannot invoke &quot;org.latiffsyed.pageobjects.android.FormPage.setActivity()&quot; because &quot;this.formPage&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "org.latiffsyed.pageobjects.android.FormPage.setActivity()" because "this.formPage" is null
	at org.latiffsyed.tests.android.PurchaseOrderFlowTest.preSetup(PurchaseOrderFlowTest.java:66)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:833)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:600)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
  </testcase>
  <testcase name="preSetup" classname="org.latiffsyed.tests.android.PurchaseOrderFlowTest" time="20.5">
    <failure message="Cannot invoke &quot;org.latiffsyed.pageobjects.android.FormPage.setActivity()&quot; because &quot;this.formPage&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "org.latiffsyed.pageobjects.android.FormPage.setActivity()" because "this.formPage" is null
	at org.latiffsyed.tests.android.PurchaseOrderFlowTest.preSetup(PurchaseOrderFlowTest.java:66)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:833)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:600)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
  </testcase>
  <testcase name="preSetup" classname="org.latiffsyed.tests.android.PurchaseOrderFlowTest" time="0.0">
    <failure message="Cannot invoke &quot;org.latiffsyed.pageobjects.android.FormPage.setActivity()&quot; because &quot;this.formPage&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "org.latiffsyed.pageobjects.android.FormPage.setActivity()" because "this.formPage" is null
	at org.latiffsyed.tests.android.PurchaseOrderFlowTest.preSetup(PurchaseOrderFlowTest.java:66)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:833)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:600)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
  </testcase>
  <testcase name="EndToEndOrderFlowTest[{gender=Female, name=Nadu Syed, country=Australia}](1)" classname="org.latiffsyed.tests.android.PurchaseOrderFlowTest" time="0.0">
    <skipped message="Cannot invoke &quot;org.latiffsyed.pageobjects.android.FormPage.setActivity()&quot; because &quot;this.formPage&quot; is null"/>
  </testcase>
  <testcase name="EndToEndOrderFlowTest[{gender=Female, name=Nadu Syed, country=Australia}](1)" classname="org.latiffsyed.tests.android.PurchaseOrderFlowTest" time="0.0">
    <skipped message="Appium HTTP server is not listening at http://127.0.0.1:4723/ after 20000 ms timeout. Consider increasing the server startup timeout value and check the server log for possible error messages occurrences.&#10;Node.js executable path: /usr/local/bin/node&#10;Arguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 127.0.0.1]&#10;Server log: &amp;#27;[38;5;112m[Appium]&amp;#27;[0m Welcome to Appium v2.19.0&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Non-default server args:&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m { address: &amp;#27;[32m&apos;127.0.0.1&apos;&amp;#27;[39m }&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m The autodetected Appium home path: /Users/administrator/.appium&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Attempting to load driver uiautomator2...&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Attempting to load driver xcuitest...&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m XCUITestDriver has been successfully loaded in 0.491s&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.923s&#10;&amp;#27;[38;5;86m[HTTP]&amp;#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Could not configure Appium server. It&apos;s possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723&#10;    at Server.setupListenHandle [as _listen2] (node:net:1939:16)&#10;    at listenInCluster (node:net:1996:12)&#10;    at node:net:2205:7&#10;    at processTicksAndRejections (node:internal/process/task_queues:90:21)&#10;"/>
  </testcase>
  <testcase name="EndToEndOrderFlowTest[{gender=Female, name=Nadu Syed, country=Australia}](1)" classname="org.latiffsyed.tests.android.PurchaseOrderFlowTest" time="0.0">
    <skipped message="Appium HTTP server is not listening at http://127.0.0.1:4723/ after 20000 ms timeout. Consider increasing the server startup timeout value and check the server log for possible error messages occurrences.&#10;Node.js executable path: /usr/local/bin/node&#10;Arguments: [/usr/local/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 127.0.0.1]&#10;Server log: &amp;#27;[38;5;112m[Appium]&amp;#27;[0m Welcome to Appium v2.19.0&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Non-default server args:&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m { address: &amp;#27;[32m&apos;127.0.0.1&apos;&amp;#27;[39m }&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m The autodetected Appium home path: /Users/administrator/.appium&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Attempting to load driver uiautomator2...&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Attempting to load driver xcuitest...&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m XCUITestDriver has been successfully loaded in 0.491s&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.923s&#10;&amp;#27;[38;5;86m[HTTP]&amp;#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Could not configure Appium server. It&apos;s possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723&#10;&amp;#27;[38;5;112m[Appium]&amp;#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723&#10;    at Server.setupListenHandle [as _listen2] (node:net:1939:16)&#10;    at listenInCluster (node:net:1996:12)&#10;    at node:net:2205:7&#10;    at processTicksAndRejections (node:internal/process/task_queues:90:21)&#10;"/>
  </testcase>
  <testcase name="tearDown" classname="org.latiffsyed.tests.android.PurchaseOrderFlowTest" time="0.034">
    <failure message="Cannot invoke &quot;io.appium.java_client.android.AndroidDriver.quit()&quot; because &quot;this.driver&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "io.appium.java_client.android.AndroidDriver.quit()" because "this.driver" is null
	at org.latiffsyed.testUtils.AndroidBaseTest.tearDown(AndroidBaseTest.java:72)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:238)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:223)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:137)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
  </testcase>
  <testcase name="tearDown" classname="org.latiffsyed.tests.android.PurchaseOrderFlowTest" time="0.034">
    <failure message="Cannot invoke &quot;io.appium.java_client.android.AndroidDriver.quit()&quot; because &quot;this.driver&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "io.appium.java_client.android.AndroidDriver.quit()" because "this.driver" is null
	at org.latiffsyed.testUtils.AndroidBaseTest.tearDown(AndroidBaseTest.java:72)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:238)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:223)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:137)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
  </testcase>
  <testcase name="tearDown" classname="org.latiffsyed.tests.android.PurchaseOrderFlowTest" time="0.036">
    <failure message="Cannot invoke &quot;io.appium.java_client.android.AndroidDriver.quit()&quot; because &quot;this.driver&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "io.appium.java_client.android.AndroidDriver.quit()" because "this.driver" is null
	at org.latiffsyed.testUtils.AndroidBaseTest.tearDown(AndroidBaseTest.java:72)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:238)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:223)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:137)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
    <system-out><![CDATA[>>> TestNG Listener: onFinish()
>>> TestNG Listener: onFinish()
]]></system-out>
  </testcase>
  <testcase name="configureAppium" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="1.634">
    <failure message="no protocol: " type="java.net.MalformedURLException"><![CDATA[java.net.MalformedURLException: no protocol: 
	at java.base/java.net.URL.<init>(URL.java:772)
	at java.base/java.net.URL.<init>(URL.java:654)
	at java.base/java.net.URL.<init>(URL.java:590)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:113)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:109)
	at org.latiffsyed.testUtils.AndroidBaseTest.configureAppium(AndroidBaseTest.java:61)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
    <system-out><![CDATA[>>> TestNG Listener: onFinish()
>>> TestNG Listener: onStart()
>>> TestNG Listener: onStart()
>>> TestNG Listener: onStart()
&amp#27;[38;5;112m[Appium]&amp#27;[0m Welcome to Appium v2.19.0
&amp#27;[38;5;112m[Appium]&amp#27;[0m Welcome to Appium v2.19.0
&amp#27;[38;5;112m[Appium]&amp#27;[0m Welcome to Appium v2.19.0
&amp#27;[38;5;112m[Appium]&amp#27;[0m Non-default server args:
&amp#27;[38;5;112m[Appium]&amp#27;[0m Non-default server args:
&amp#27;[38;5;112m[Appium]&amp#27;[0m Non-default server args:
&amp#27;[38;5;112m[Appium]&amp#27;[0m { address: &amp#27;[32m'127.0.0.1'&amp#27;[39m }
&amp#27;[38;5;112m[Appium]&amp#27;[0m { address: &amp#27;[32m'127.0.0.1'&amp#27;[39m }
&amp#27;[38;5;112m[Appium]&amp#27;[0m { address: &amp#27;[32m'127.0.0.1'&amp#27;[39m }
&amp#27;[38;5;112m[Appium]&amp#27;[0m The autodetected Appium home path: /Users/administrator/.appium
&amp#27;[38;5;112m[Appium]&amp#27;[0m The autodetected Appium home path: /Users/administrator/.appium
&amp#27;[38;5;112m[Appium]&amp#27;[0m The autodetected Appium home path: /Users/administrator/.appium
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver uiautomator2...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver uiautomator2...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver uiautomator2...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver xcuitest...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver xcuitest...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver xcuitest...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.326s
&amp#27;[38;5;112m[Appium]&amp#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.326s
&amp#27;[38;5;112m[Appium]&amp#27;[0m XCUITestDriver has been successfully loaded in 0.379s
&amp#27;[38;5;112m[Appium]&amp#27;[0m XCUITestDriver has been successfully loaded in 0.508s
&amp#27;[38;5;112m[Appium]&amp#27;[0m XCUITestDriver has been successfully loaded in 0.508s
&amp#27;[38;5;86m[HTTP]&amp#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
&amp#27;[38;5;112m[Appium]&amp#27;[0m Appium REST http interface listener started on http://127.0.0.1:4723
&amp#27;[38;5;112m[Appium]&amp#27;[0m Available drivers:
&amp#27;[38;5;112m[Appium]&amp#27;[0m   - uiautomator2@4.2.3 (automationName 'UiAutomator2')
&amp#27;[38;5;112m[Appium]&amp#27;[0m   - xcuitest@9.9.1 (automationName 'XCUITest')
&amp#27;[38;5;112m[Appium]&amp#27;[0m No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
&amp#27;[38;5;112m[Appium]&amp#27;[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
&amp#27;[38;5;112m[Appium]&amp#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (node:net:1939:16)
    at listenInCluster (node:net:1996:12)
    at node:net:2205:7
    at processTicksAndRejections (node:internal/process/task_queues:90:21)
&amp#27;[38;5;112m[Appium]&amp#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.536s
&amp#27;[38;5;86m[HTTP]&amp#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
&amp#27;[38;5;112m[Appium]&amp#27;[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
&amp#27;[38;5;112m[Appium]&amp#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (node:net:1939:16)
    at listenInCluster (node:net:1996:12)
    at node:net:2205:7
    at processTicksAndRejections (node:internal/process/task_queues:90:21)
&amp#27;[38;5;86m[HTTP]&amp#27;[0m &amp#27;[37m-->&amp#27;[39m &amp#27;[37mGET&amp#27;[39m &amp#27;[37m/status&amp#27;[39m &amp#27;[90m{}&amp#27;[39m
&amp#27;[38;5;218m[AppiumDriver@03c8]&amp#27;[0m Calling AppiumDriver.getStatus() with args: []
&amp#27;[38;5;218m[AppiumDriver@03c8]&amp#27;[0m Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.19.0"}}
&amp#27;[38;5;86m[HTTP]&amp#27;[0m &amp#27;[37m<-- GET /status &amp#27;[39m&amp#27;[32m200&amp#27;[39m &amp#27;[90m4 ms - 111&amp#27;[39m &amp#27;[90m&amp#27;[39m
&amp#27;[38;5;86m[HTTP]&amp#27;[0m &amp#27;[37m-->&amp#27;[39m &amp#27;[37mGET&amp#27;[39m &amp#27;[37m/status&amp#27;[39m &amp#27;[90m{}&amp#27;[39m
&amp#27;[38;5;218m[AppiumDriver@03c8]&amp#27;[0m Calling AppiumDriver.getStatus() with args: []
&amp#27;[38;5;218m[AppiumDriver@03c8]&amp#27;[0m Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.19.0"}}
&amp#27;[38;5;86m[HTTP]&amp#27;[0m &amp#27;[37m<-- GET /status &amp#27;[39m&amp#27;[32m200&amp#27;[39m &amp#27;[90m1 ms - 111&amp#27;[39m &amp#27;[90m&amp#27;[39m
&amp#27;[38;5;86m[HTTP]&amp#27;[0m &amp#27;[37m-->&amp#27;[39m &amp#27;[37mGET&amp#27;[39m &amp#27;[37m/status&amp#27;[39m &amp#27;[90m{}&amp#27;[39m
&amp#27;[38;5;218m[AppiumDriver@03c8]&amp#27;[0m Calling AppiumDriver.getStatus() with args: []
&amp#27;[38;5;218m[AppiumDriver@03c8]&amp#27;[0m Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.19.0"}}
&amp#27;[38;5;86m[HTTP]&amp#27;[0m &amp#27;[37m<-- GET /status &amp#27;[39m&amp#27;[32m200&amp#27;[39m &amp#27;[90m0 ms - 111&amp#27;[39m &amp#27;[90m&amp#27;[39m
]]></system-out>
  </testcase>
  <testcase name="configureAppium" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="1.635">
    <failure message="no protocol: " type="java.net.MalformedURLException"><![CDATA[java.net.MalformedURLException: no protocol: 
	at java.base/java.net.URL.<init>(URL.java:772)
	at java.base/java.net.URL.<init>(URL.java:654)
	at java.base/java.net.URL.<init>(URL.java:590)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:113)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:109)
	at org.latiffsyed.testUtils.AndroidBaseTest.configureAppium(AndroidBaseTest.java:61)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
  </testcase>
  <testcase name="configureAppium" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="1.638">
    <failure message="no protocol: " type="java.net.MalformedURLException"><![CDATA[java.net.MalformedURLException: no protocol: 
	at java.base/java.net.URL.<init>(URL.java:772)
	at java.base/java.net.URL.<init>(URL.java:654)
	at java.base/java.net.URL.<init>(URL.java:590)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:113)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:109)
	at org.latiffsyed.testUtils.AndroidBaseTest.configureAppium(AndroidBaseTest.java:61)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
  </testcase>
  <testcase name="preSetup" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="preSetup" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="preSetup" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="preSetup" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="preSetup" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="preSetup" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="preSetup" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="preSetup" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="preSetup" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="FormLogin_ErrorValidationFailedTest" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped message="no protocol: "/>
  </testcase>
  <testcase name="FormLogin_ErrorValidationFailedTest" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped message="no protocol: "/>
  </testcase>
  <testcase name="FormLogin_ErrorValidationFailedTest" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped message="no protocol: "/>
  </testcase>
  <testcase name="FormLogin_ErrorValidationTest" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped message="no protocol: "/>
  </testcase>
  <testcase name="FormLogin_ErrorValidationTest" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped message="no protocol: "/>
  </testcase>
  <testcase name="FormLogin_ErrorValidationTest" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped message="no protocol: "/>
  </testcase>
  <testcase name="FormLogin_PositiveFlowTest" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped message="no protocol: "/>
  </testcase>
  <testcase name="FormLogin_PositiveFlowTest" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped message="no protocol: "/>
  </testcase>
  <testcase name="FormLogin_PositiveFlowTest" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.0">
    <skipped message="no protocol: "/>
  </testcase>
  <testcase name="tearDown" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.26">
    <failure message="Cannot invoke &quot;io.appium.java_client.android.AndroidDriver.quit()&quot; because &quot;this.driver&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "io.appium.java_client.android.AndroidDriver.quit()" because "this.driver" is null
	at org.latiffsyed.testUtils.AndroidBaseTest.tearDown(AndroidBaseTest.java:72)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:238)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:223)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:137)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
  </testcase>
  <testcase name="tearDown" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.269">
    <failure message="Cannot invoke &quot;io.appium.java_client.android.AndroidDriver.quit()&quot; because &quot;this.driver&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "io.appium.java_client.android.AndroidDriver.quit()" because "this.driver" is null
	at org.latiffsyed.testUtils.AndroidBaseTest.tearDown(AndroidBaseTest.java:72)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:238)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:223)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:137)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
    <system-out><![CDATA[>>> TestNG Listener: onFinish()
>>> TestNG Listener: onStart()
]]></system-out>
  </testcase>
  <testcase name="tearDown" classname="org.latiffsyed.tests.android.LoginFormValidationTest" time="0.15">
    <failure message="Cannot invoke &quot;io.appium.java_client.android.AndroidDriver.quit()&quot; because &quot;this.driver&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "io.appium.java_client.android.AndroidDriver.quit()" because "this.driver" is null
	at org.latiffsyed.testUtils.AndroidBaseTest.tearDown(AndroidBaseTest.java:72)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:238)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:223)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:137)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
  </testcase>
  <testcase name="configureAppium" classname="org.latiffsyed.tests.iOS.AlertViewMessageValidationTest" time="0.293">
    <failure message="no protocol: " type="java.net.MalformedURLException"><![CDATA[java.net.MalformedURLException: no protocol: 
	at java.base/java.net.URL.<init>(URL.java:772)
	at java.base/java.net.URL.<init>(URL.java:654)
	at java.base/java.net.URL.<init>(URL.java:590)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:113)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:101)
	at org.latiffsyed.testUtils.IOSBaseTest.configureAppium(IOSBaseTest.java:61)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
    <system-out><![CDATA[>>> TestNG Listener: onFinish()
>>> TestNG Listener: onStart()
&amp#27;[38;5;86m[HTTP]&amp#27;[0m &amp#27;[37m-->&amp#27;[39m &amp#27;[37mGET&amp#27;[39m &amp#27;[37m/status&amp#27;[39m &amp#27;[90m{}&amp#27;[39m
&amp#27;[38;5;218m[AppiumDriver@03c8]&amp#27;[0m Calling AppiumDriver.getStatus() with args: []
&amp#27;[38;5;218m[AppiumDriver@03c8]&amp#27;[0m Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.19.0"}}
&amp#27;[38;5;86m[HTTP]&amp#27;[0m &amp#27;[37m<-- GET /status &amp#27;[39m&amp#27;[32m200&amp#27;[39m &amp#27;[90m0 ms - 111&amp#27;[39m &amp#27;[90m&amp#27;[39m
&amp#27;[38;5;86m[HTTP]&amp#27;[0m &amp#27;[37m-->&amp#27;[39m &amp#27;[37mGET&amp#27;[39m &amp#27;[37m/status&amp#27;[39m &amp#27;[90m{}&amp#27;[39m
&amp#27;[38;5;218m[AppiumDriver@03c8]&amp#27;[0m Calling AppiumDriver.getStatus() with args: []
&amp#27;[38;5;218m[AppiumDriver@03c8]&amp#27;[0m Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.19.0"}}
&amp#27;[38;5;86m[HTTP]&amp#27;[0m &amp#27;[37m<-- GET /status &amp#27;[39m&amp#27;[32m200&amp#27;[39m &amp#27;[90m1 ms - 111&amp#27;[39m &amp#27;[90m&amp#27;[39m
]]></system-out>
  </testcase>
  <testcase name="configureAppium" classname="org.latiffsyed.tests.iOS.AlertViewMessageValidationTest" time="0.005">
    <failure message="no protocol: " type="java.net.MalformedURLException"><![CDATA[java.net.MalformedURLException: no protocol: 
	at java.base/java.net.URL.<init>(URL.java:772)
	at java.base/java.net.URL.<init>(URL.java:654)
	at java.base/java.net.URL.<init>(URL.java:590)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:113)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:101)
	at org.latiffsyed.testUtils.IOSBaseTest.configureAppium(IOSBaseTest.java:61)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
  </testcase>
  <testcase name="configureAppium" classname="org.latiffsyed.tests.iOS.AlertViewMessageValidationTest" time="0.177">
    <failure message="no protocol: " type="java.net.MalformedURLException"><![CDATA[java.net.MalformedURLException: no protocol: 
	at java.base/java.net.URL.<init>(URL.java:772)
	at java.base/java.net.URL.<init>(URL.java:654)
	at java.base/java.net.URL.<init>(URL.java:590)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:113)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:101)
	at org.latiffsyed.testUtils.IOSBaseTest.configureAppium(IOSBaseTest.java:61)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
    <system-out><![CDATA[>>> TestNG Listener: onFinish()
>>> TestNG Listener: onStart()
&amp#27;[38;5;86m[HTTP]&amp#27;[0m &amp#27;[37m-->&amp#27;[39m &amp#27;[37mGET&amp#27;[39m &amp#27;[37m/status&amp#27;[39m &amp#27;[90m{}&amp#27;[39m
&amp#27;[38;5;218m[AppiumDriver@03c8]&amp#27;[0m Calling AppiumDriver.getStatus() with args: []
&amp#27;[38;5;218m[AppiumDriver@03c8]&amp#27;[0m Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.19.0"}}
&amp#27;[38;5;86m[HTTP]&amp#27;[0m &amp#27;[37m<-- GET /status &amp#27;[39m&amp#27;[32m200&amp#27;[39m &amp#27;[90m1 ms - 111&amp#27;[39m &amp#27;[90m&amp#27;[39m
]]></system-out>
  </testcase>
  <testcase name="ValidateiOSAlertMessageTest" classname="org.latiffsyed.tests.iOS.AlertViewMessageValidationTest" time="0.0">
    <skipped message="no protocol: "/>
    <system-out><![CDATA[&amp#27;[38;5;112m[Appium]&amp#27;[0m Welcome to Appium v2.19.0
&amp#27;[38;5;112m[Appium]&amp#27;[0m Welcome to Appium v2.19.0
&amp#27;[38;5;112m[Appium]&amp#27;[0m Non-default server args:
&amp#27;[38;5;112m[Appium]&amp#27;[0m Non-default server args:
&amp#27;[38;5;112m[Appium]&amp#27;[0m { address: &amp#27;[32m'127.0.0.1'&amp#27;[39m }
&amp#27;[38;5;112m[Appium]&amp#27;[0m { address: &amp#27;[32m'127.0.0.1'&amp#27;[39m }
&amp#27;[38;5;112m[Appium]&amp#27;[0m The autodetected Appium home path: /Users/administrator/.appium
&amp#27;[38;5;112m[Appium]&amp#27;[0m The autodetected Appium home path: /Users/administrator/.appium
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver uiautomator2...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver uiautomator2...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver xcuitest...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver xcuitest...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.166s
&amp#27;[38;5;112m[Appium]&amp#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.169s
&amp#27;[38;5;112m[Appium]&amp#27;[0m Welcome to Appium v2.19.0
&amp#27;[38;5;112m[Appium]&amp#27;[0m Non-default server args:
&amp#27;[38;5;112m[Appium]&amp#27;[0m { address: &amp#27;[32m'127.0.0.1'&amp#27;[39m }
&amp#27;[38;5;112m[Appium]&amp#27;[0m The autodetected Appium home path: /Users/administrator/.appium
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver uiautomator2...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Attempting to load driver xcuitest...
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-uiautomator2-driver/build/index.js
&amp#27;[38;5;112m[Appium]&amp#27;[0m Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver/build/index.js
]]></system-out>
  </testcase>
  <testcase name="ValidateiOSAlertMessageTest" classname="org.latiffsyed.tests.iOS.AlertViewMessageValidationTest" time="0.0">
    <skipped message="no protocol: "/>
  </testcase>
  <testcase name="ValidateiOSAlertMessageTest" classname="org.latiffsyed.tests.iOS.AlertViewMessageValidationTest" time="0.0">
    <skipped message="no protocol: "/>
    <system-out><![CDATA[>>> TestNG Listener: onFinish()
&amp#27;[38;5;112m[Appium]&amp#27;[0m XCUITestDriver has been successfully loaded in 0.374s
&amp#27;[38;5;86m[HTTP]&amp#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
&amp#27;[38;5;112m[Appium]&amp#27;[0m XCUITestDriver has been successfully loaded in 0.383s
&amp#27;[38;5;112m[Appium]&amp#27;[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
&amp#27;[38;5;112m[Appium]&amp#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (node:net:1939:16)
    at listenInCluster (node:net:1996:12)
    at node:net:2205:7
    at processTicksAndRejections (node:internal/process/task_queues:90:21)
&amp#27;[38;5;86m[HTTP]&amp#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
&amp#27;[38;5;112m[Appium]&amp#27;[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
&amp#27;[38;5;112m[Appium]&amp#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (node:net:1939:16)
    at listenInCluster (node:net:1996:12)
    at node:net:2205:7
    at processTicksAndRejections (node:internal/process/task_queues:90:21)
&amp#27;[38;5;112m[Appium]&amp#27;[0m AndroidUiautomator2Driver has been successfully loaded in 0.188s
&amp#27;[38;5;112m[Appium]&amp#27;[0m XCUITestDriver has been successfully loaded in 0.345s
&amp#27;[38;5;86m[HTTP]&amp#27;[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
&amp#27;[38;5;112m[Appium]&amp#27;[0m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
&amp#27;[38;5;112m[Appium]&amp#27;[0m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
    at Server.setupListenHandle [as _listen2] (node:net:1939:16)
    at listenInCluster (node:net:1996:12)
    at node:net:2205:7
    at processTicksAndRejections (node:internal/process/task_queues:90:21)
]]></system-out>
  </testcase>
  <testcase name="tearDown" classname="org.latiffsyed.tests.iOS.AlertViewMessageValidationTest" time="0.336">
    <failure message="Cannot invoke &quot;io.appium.java_client.ios.IOSDriver.quit()&quot; because &quot;this.driver&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "io.appium.java_client.ios.IOSDriver.quit()" because "this.driver" is null
	at org.latiffsyed.testUtils.IOSBaseTest.tearDown(IOSBaseTest.java:71)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:238)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:223)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:137)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
  </testcase>
  <testcase name="tearDown" classname="org.latiffsyed.tests.iOS.AlertViewMessageValidationTest" time="0.361">
    <failure message="Cannot invoke &quot;io.appium.java_client.ios.IOSDriver.quit()&quot; because &quot;this.driver&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "io.appium.java_client.ios.IOSDriver.quit()" because "this.driver" is null
	at org.latiffsyed.testUtils.IOSBaseTest.tearDown(IOSBaseTest.java:71)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:238)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:223)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:137)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
    <system-out><![CDATA[>>> TestNG Listener: onFinish()
]]></system-out>
  </testcase>
  <testcase name="tearDown" classname="org.latiffsyed.tests.iOS.AlertViewMessageValidationTest" time="0.626">
    <failure message="Cannot invoke &quot;io.appium.java_client.ios.IOSDriver.quit()&quot; because &quot;this.driver&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "io.appium.java_client.ios.IOSDriver.quit()" because "this.driver" is null
	at org.latiffsyed.testUtils.IOSBaseTest.tearDown(IOSBaseTest.java:71)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:238)
	at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:223)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:137)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:739)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]></failure>
  </testcase>
</testsuite>